### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by honguyenminh** [Kinue72/AdlistCollecting#1]
Làm cái .gitignore rồi thêm mấy cái bin obj đồ vào đấy đi bro, sao lại up binary lên repo thế này

**Comment by Kinue72** [comment]
up lên cho tiện

**Comment by honguyenminh** [comment]
I... Don't think that's how git supposed to work...

Eh fair enough.

Lần sau, binary nhét vào tab release, và ignore mọi file binary đi nhá, track file binary trong git nó vô nghĩa lắm
